In [9]:
from keras.models import Sequential
from keras.layers import Convolution2D, ZeroPadding2D ,BatchNormalization
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense , Dropout
import tensorflow as tf
print(tf.__version__)
import PIL

1.14.0


In [10]:
classifier = Sequential()

In [11]:
#step1-convolution
classifier.add(Convolution2D(16,(2,2),input_shape=(256,256,3),activation='relu'))
classifier.add(BatchNormalization(momentum=0.9))
classifier.add(Convolution2D(32,(4,4),activation='relu'))

#step2-pooling
classifier.add(MaxPooling2D((2,2)))

#adding second Convolution layer
classifier.add(Dropout(0.2))
classifier.add(Convolution2D(64,(4,4),activation='relu'))
classifier.add(BatchNormalization())
classifier.add(Convolution2D(64,(4,2),activation='relu'))
classifier.add(BatchNormalization())
classifier.add(MaxPooling2D((2,2)))
classifier.add(Dropout(0.2))

#adding third Convolution layer
classifier.add(Convolution2D(64,(4,2),activation='relu'))
classifier.add(BatchNormalization())

#adding third Convolution layer
classifier.add(MaxPooling2D((2,2)))
classifier.add(Flatten())

#step4-full connection
classifier.add(Dense(activation='relu',units=128))

classifier.add(BatchNormalization())
classifier.add(Dropout(0.2))
classifier.add(Dense(activation='relu',units=128))
classifier.add(BatchNormalization())
classifier.add(Dropout(0.2))
classifier.add(Dense(activation='softmax',units=3))

W0730 18:50:37.585427 140087561643840 deprecation_wrapper.py:119] From /home/prajjwal/anaconda3/envs/machinelearning/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0730 18:50:37.695472 140087561643840 deprecation_wrapper.py:119] From /home/prajjwal/anaconda3/envs/machinelearning/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0730 18:50:37.783730 140087561643840 deprecation_wrapper.py:119] From /home/prajjwal/anaconda3/envs/machinelearning/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0730 18:50:37.784545 140087561643840 deprecation_wrapper.py:119] From /home/prajjwal/anaconda3/envs/machinelearning/lib/python3.6/site-packages/keras/backend/tensorflow_back

In [12]:
#compiling the cnn
classifier.compile(optimizer='adam' , loss='categorical_crossentropy',metrics=['accuracy'])

In [13]:
#part2- fitting the CNN to the images
from keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(rescale=1./255)

test_datagen = ImageDataGenerator(rescale=1./255)

In [14]:
training_set = train_datagen.flow_from_directory('DS/train',
        target_size=(256,256),
        batch_size=32,
        color_mode='rgb',
        class_mode='categorical')

test_set = test_datagen.flow_from_directory(
        'DS/test',
        target_size=(256,256),
        batch_size=32,
        color_mode='rgb',
        class_mode='categorical')


Found 239 images belonging to 3 classes.
Found 60 images belonging to 3 classes.


In [15]:
H=classifier.fit_generator(training_set,
        steps_per_epoch=50,
        epochs=10,
        validation_data=test_set,
        validation_steps=20)

W0730 18:50:40.351485 140087561643840 deprecation.py:323] From /home/prajjwal/anaconda3/envs/machinelearning/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/10
50/50 [==============================] - 401s 8s/step - loss: 0.5972 - acc: 0.8029 - val_loss: 1.8826 - val_acc: 0.6500
Epoch 2/10
50/50 [==============================] - 264s 5s/step - loss: 0.1240 - acc: 0.9691 - val_loss: 0.8327 - val_acc: 0.7000
Epoch 3/10
50/50 [==============================] - 266s 5s/step - loss: 0.0664 - acc: 0.9886 - val_loss: 1.2106 - val_acc: 0.6833
Epoch 4/10
50/50 [==============================] - 267s 5s/step - loss: 0.0446 - acc: 0.9879 - val_loss: 1.6829 - val_acc: 0.6167
Epoch 5/10
50/50 [==============================] - 268s 5s/step - loss: 0.0163 - acc: 0.9981 - val_loss: 1.4735 - val_acc: 0.5500
Epoch 6/10
50/50 [==============================] - 268s 5s/step - loss: 0.0390 - acc: 0.9911 - val_loss: 2.7921 - val_acc: 0.5500
Epoch 7/10
50/50 [==============================] - 263s 5s/step - loss: 0.0373 - acc: 0.9886 - val_loss: 4.4028 - val_acc: 0.5000
Epoch 8/10
50/50 [==============================] - 266s 5s/step - loss: 0.0162 - a

In [16]:
import pickle
saved_model = pickle.dumps('classifier')

In [17]:
load_model = pickle.loads(saved_model)

In [19]:
classifier.save('my_model.h5')


In [21]:
fname = "my_model.h5"
classifier.load_weights(fname)

In [22]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 255, 255, 16)      208       
_________________________________________________________________
batch_normalization_1 (Batch (None, 255, 255, 16)      64        
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 252, 252, 32)      8224      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 126, 126, 32)      0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 126, 126, 32)      0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 123, 123, 64)      32832     
_________________________________________________________________
batch_normalization_2 (Batch (None, 123, 123, 64)      256       
__________

In [23]:
classifier.predict_generator(test_set,steps = len(test_set))

array([[1.5158136e-03, 9.9817467e-01, 3.0954534e-04],
       [9.9904484e-01, 1.8869690e-05, 9.3633472e-04],
       [8.8087516e-04, 9.9879044e-01, 3.2876278e-04],
       [8.5306738e-04, 5.7514982e-05, 9.9908948e-01],
       [8.7093270e-01, 1.1862266e-03, 1.2788114e-01],
       [9.0857542e-01, 1.4591255e-03, 8.9965373e-02],
       [6.2016714e-01, 3.4464322e-06, 3.7982932e-01],
       [3.3824807e-03, 9.9479997e-01, 1.8175386e-03],
       [3.4781080e-03, 9.9521351e-01, 1.3083885e-03],
       [2.5232943e-02, 3.1133384e-01, 6.6343325e-01],
       [4.8325571e-01, 3.9554192e-03, 5.1278883e-01],
       [1.4059837e-01, 8.5382509e-01, 5.5764890e-03],
       [9.9998081e-01, 1.4822892e-10, 1.9251185e-05],
       [7.8396007e-02, 8.3444041e-01, 8.7163530e-02],
       [9.9709058e-01, 1.0952190e-08, 2.9094508e-03],
       [1.9473324e-02, 9.7674233e-01, 3.7842533e-03],
       [1.8505567e-03, 9.9667573e-01, 1.4737576e-03],
       [6.9850758e-02, 9.0051150e-01, 2.9637722e-02],
       [9.7855592e-01, 2.111

In [31]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
e=test_set.classes
Y_pred = classifier.predict_generator(test_set,60 // 32+1)
y_pred = np.argmax(Y_pred, axis=1)
print('Confusion Matrix')
s=confusion_matrix(e,y_pred) 
print(s)

Confusion Matrix
[[ 9  8  3]
 [ 6 11  3]
 [ 7  9  4]]
