In [1]:
from sklearn.externals import joblib

/home/prajjwal/anaconda3/envs/machinelearning/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [2]:
loaded_model = joblib.load('finalized_CNNmodel.sav')
loaded_model.layers[0].input_shape

Using TensorFlow backend.
W0731 11:22:40.211084 139997483325248 deprecation_wrapper.py:119] From /home/prajjwal/anaconda3/envs/machinelearning/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0731 11:22:40.230648 139997483325248 deprecation_wrapper.py:119] From /home/prajjwal/anaconda3/envs/machinelearning/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0731 11:22:40.262321 139997483325248 deprecation_wrapper.py:119] From /home/prajjwal/anaconda3/envs/machinelearning/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:245: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0731 11:22:40.263000 139997483325248 deprecation_wrapper.py:119] From /home/prajjwal/anaconda3/envs/machinelearning/lib/python3.6/site-packages/keras/b

(None, 256, 256, 3)

In [3]:
from keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(rescale=0)

test_datagen = ImageDataGenerator(rescale=0)

test_set = test_datagen.flow_from_directory(
        'dataset/test',
        target_size=(256, 256),
        batch_size=32,
        color_mode='rgb',
        class_mode='categorical')

Found 360 images belonging to 3 classes.


In [4]:
loaded_model.predict_generator(test_set,steps = len(test_set))

array([[1.13911769e-09, 1.00000000e+00, 3.00746997e-11],
       [4.23420489e-01, 5.42971939e-05, 5.76525211e-01],
       [7.23594785e-01, 5.87321178e-04, 2.75817931e-01],
       ...,
       [2.65700696e-03, 9.88791227e-01, 8.55176337e-03],
       [7.06770341e-04, 9.98672247e-01, 6.20922598e-04],
       [9.99983072e-01, 1.69207215e-05, 1.20459775e-08]], dtype=float32)

In [5]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
e=test_set.classes
Y_pred = loaded_model.predict_generator(test_set,360//32+1)
y_pred = np.argmax(Y_pred, axis=1)
print('Confusion Matrix')
s=confusion_matrix(test_set.classes,y_pred)
print(s)

Confusion Matrix
[[48 46 26]
 [40 55 25]
 [36 50 34]]


In [6]:
loaded_model.compile(loss='categorical_crossentropy',
                    optimizer='adam',
                    metrics=['accuracy'])


In [7]:
# make predictions on the testing images, finding the index of the
# label with the corresponding largest predicted probability
NUM=360
BS=32
predIdxs = loaded_model.predict_generator(test_set,steps=(NUM // BS) + 1)
predIdxs = np.argmax(predIdxs, axis=1)
testLabels=test_set.classes
target_names=[0,1,2]

# show a nicely formatted classification report
print("[INFO] evaluating network...")
print(classification_report(testLabels, predIdxs,
	target_names))


[INFO] evaluating network...
              precision    recall  f1-score   support

           0       0.34      0.36      0.35       120
           1       0.34      0.43      0.38       120
           2       0.31      0.21      0.25       120

    accuracy                           0.33       360
   macro avg       0.33      0.33      0.33       360
weighted avg       0.33      0.33      0.33       360



In [18]:
#single prediction
import numpy as np
import cv2
from keras.preprocessing import image

test_image=image.load_img('music2.png',target_size=(256,256), color_mode='rgb')
test_image=image.img_to_array(test_image)
test_image=np.expand_dims(test_image,axis=0)
result=loaded_model.predict(test_image)
genre = np.argmax(result)
if(genre == 0):
    print('Classical')
elif(genre == 1):
    print('Dohori')
else:
    print('Pop')

      

Pop
